### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by paramsiddharth** [todi-2000/Quiz-App#15]
# Fix .gitignore to ignore unwanted files
The `.gitignore` file is erroneous and pollutants are allowed persist in the repository.

## Fixes
- Update and create more `.gitignore` files as needed to stop certain files/folders from being committed to the repository.
- Remove the pollutants from Git cache such that newer commits don't include them.

If approved, I would like to work on this issue.

**Comment by todi-2000** [comment]
Yes Sure, go ahead
