### ISSUE TITLE
Automatically level increment for added question

### ISSUE THREAD

**Issue by SubhradeepSS** [todi-2000/Quiz-App#37]
**Is your feature request related to a problem? Please describe.**
Currently, whenever a question is added by admin, the level requires to be added manually and the admin must also ensure that every time a new question is added the level is 1+level of previous question. This makes it a bit tedious for the admin.

**Describe the solution you'd like**
The level `field` of `Question`model can be changed to **autoincrement** and a default value can be set for first question.

**Comment by SubhradeepSS** [comment]
@todi-2000 I want to work on this issue if you are fine with the idea.

**Comment by todi-2000** [comment]
You can go ahead.
