### ISSUE TITLE
Tags for question

### ISSUE THREAD

**Issue by SubhradeepSS** [todi-2000/Quiz-App#41]
**Is your feature request related to a problem? Please describe.**
Different tags can be attached to a question like #tough,#easy,#difficult,etc for future enhancement features.

**Describe the solution you'd like**
Adding an extra field tags for model Post by using [django-taggit](https://django-taggit.readthedocs.io/en/latest/)

**Comment by todi-2000** [comment]
If you would like to work on this issue. You can go ahead.

**Comment by SubhradeepSS** [comment]
> 
> 
> If you would like to work on this issue. You can go ahead.

Can u assign it to me so that no one starts working on it?
