### ISSUE TITLE
Timer reset on reloading question

### ISSUE THREAD

**Issue by SubhradeepSS** [todi-2000/Quiz-App#46]
**Describe the bug**
The timer resets to 2 minutes on reloading the question page.

**To Reproduce**
1. Reload any question page
2. The timer resets to 2 minutes

**Expected behavior**
The timer for a question should not reset on page reload.

**Comment by SubhradeepSS** [comment]
@todi-2000 I want to work on this issue.

**Comment by todi-2000** [comment]
Go Ahead.
