### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Aayush-hub** [todi-2000/Quiz-App#53]
**Describe the bug**
Not able to give input in password section.

**To Reproduce**
1. - Fork and Clone the repo:

```
git clone https://github.com/todi-2000/Quiz-App.git
```

2. - Create virtual environment:

```
python -m venv env
env\Scripts\activate
```

3. - Install dependencies using

```
pip install -r requirements.txt
```
4. - Change Directory:

```
cd quizz
```
5. - Make migrations using

```
python manage.py makemigrations
```

6. - Migrate Database

```
python manage.py migrate
```

7. - Create a superuser

```
python manage.py createsuperuser
```

**Expected behavior**
The terminal should take input for password.

**Actual behavior**
The user is unable to enter any sort of element in front of password.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/65889104/103194918-16bcc200-4907-11eb-9478-e342a06988bc.JPG)

**Comment by todi-2000** [comment]
@Aayush-hub This is not any bug. For security purpose password is hidden.
I am closing this issue.

**Comment by Aayush-hub** [comment]
@todi-2000 Sorry for that mam, this was unknown to me:)
