### ISSUE TITLE
Quiz Ending Page

### ISSUE THREAD

**Issue by todi-2000** [todi-2000/Quiz-App#6]
## Explanation
Make a ending page with Thankyou note and displaying score of user after the end of quiz.

**Comment by khushi0704** [comment]
Can you please assign me this issue ? @todi-2000 I can code in all (python , html ,css )

**Comment by todi-2000** [comment]
Yes, go ahead

**Comment by sammy8825** [comment]
Can you assign me this issue @todi-2000? I can also code in all (python, HTML, and CSS)

**Comment by khushi0704** [comment]
@todi-2000 Kindly please send the discord channel link

**Comment by todi-2000** [comment]
Okay Sure https://discord.gg/pVjcyPtwGx
